INSERT INTO ROOM (ID,TITLE, SIZE,CREATED_AT) VALUES (1,'GREEN', 30 ,CURRENT_TIMESTAMP);
INSERT INTO ANIMAL(ID, TITLE, CREATED_AT, TYPE, ROOM_ID) VALUES (1, 'DOG', CURRENT_TIMESTAMP, '<=34', 1);
INSERT INTO ANIMAL(ID, TITLE, CREATED_AT, TYPE) VALUES (2, 'CAT', CURRENT_TIMESTAMP, '<=15');
INSERT INTO ANIMAL(ID, TITLE, CREATED_AT, TYPE, ROOM_ID) VALUES (3, 'GOAT', CURRENT_TIMESTAMP, '<=34', 1);
