CREATE TABLE ANIMAL(
ID BIGINT NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
CREATEDAT TIMESTAMP ,
TYPE VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE ROOM(
ID BIGINT NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(255) NOT NULL,
SIZE INTEGER NOT NULL,
CREATEDAT TIMESTAMP ,
PRIMARY KEY (ID)
);

CREATE TABLE FAVOURITE(
ID BIGINT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID)
);

